# Generated by Django 3.2 on 2021-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_auto_20210416_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='exam',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='example',
            name='focus',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='example',
            name='level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='start',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='example',
            name='temperature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
