# Generated by Django 3.2 on 2021-04-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_auto_20210416_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150, unique=True),
        ),
    ]
