# Generated by Django 3.2 on 2021-04-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0004_alter_example_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='level',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
